### ISSUE TITLE
Change wiki to use HTTPS instead of SSH

### ISSUE THREAD

**Issue by ejball** [Faithlife/CSharpTemplate#16]
Should we prefer remotes to use HTTPS (e.g. https://github.com/Faithlife/CSharpTemplate.git) instead of SSH? Or provide both options?

**Comment by bgrainger** [comment]
I think I recommended that because I already had a public/private keypair set up, and authentication happens "automatically". I haven't done HTTPS with GitHub.com enough to know if it's smart enough to prompt for credentials once, then save them (or, in general, how authentication is handled).

**Comment by ejball** [comment]
I confess, I use SmartGit for just about everything. I don't even know if I can push from Git Bash. 😊 

But supposedly it is possible to [cache credentials](https://help.github.com/en/articles/caching-your-github-password-in-git) when using HTTPS.

**Comment by ejball** [comment]
Also, we use HTTPS in https://github.com/Faithlife/CSharpTemplate/blob/template/CONTRIBUTING.md

**Comment by bgrainger** [comment]
No objection to HTTPS.

**Comment by ejball** [comment]
Fixed.
