### ISSUE TITLE
Move docs from gh_pages branch to docs folder

### ISSUE THREAD

**Issue by ejball** [Faithlife/CSharpTemplate#18]
Editing `gh_pages` is a pain, so documentation gets neglected. #9 should minimize the churn on `master` as the API changes.

**Comment by bgrainger** [comment]
As well as the template code, this section of the wiki would need to be updated: https://github.com/Faithlife/CSharpTemplate/wiki#create-a-gh-pages-branch-for-documentation

**Comment by ejball** [comment]
FWIW, this is done on the `faithlife-build` branch.
